paginate = 4
baseURL = "https://ch0992.github.io/techblog/"
languageCode = "en-us"
title = "Ethan (Yeong Gyu) Choi"
theme = "PaperMod"

[params]
  defaultTheme = "dark"
  description = "Personal Tech Blog by Ethan (Yeong Gyu) Choi"
  author = "Ethan (Yeong Gyu) Choi"
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  disableSpecial1stPost = true
  showDescription = true

  [params.profileMode]
    enabled = true
    title = "Ethan (Yeong Gyu) Choi"
    subtitle = "Documenting what I learn in Cloud, DevOps, and AI."
    imageUrl = "/techblog/images/icons/logo_icon.png"
    imageTitle = "Ethan (Yeong Gyu) Choi"
    imageWidth = 150
    imageHeight = 150

    [[params.profileMode.buttons]]
      name = "Posts"
      url = "/techblog/posts/"
    [[params.profileMode.buttons]]
      name = "About"
      url = "/techblog/about/"

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/ch0992"
  [[params.socialIcons]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/yeong-gyu-choi-32355b174/"

[menu]
  [[menu.main]]
    name = "All Posts"
    url = "/posts/"
    weight = 10
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 20

